config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'dashboard/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'dashboard#index'
  resources :posts do
    collection do
      get :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  settings do
    mappings dynamic: false do
      indexes :author, type: :text
      indexes :title, type: :text, analyzer: :english
      indexes :body, type: :text, analyzer: :english
      indexes :tags, type: :text, analyzer: :english
      indexes :published, type: :boolean
    end
  end

  def self.search_published(query)
    search({
             query: {
               bool: {
                 must: [
                   {
                     multi_match: {
                       query: query,
                       fields: %i[author title body tags]
                     }
                   },
                   {
                     match: {
                       published: true
                     }
                   }
                 ]
               }
             }
           })
         end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

require 'hashie'
require 'elasticsearch'
require 'elasticsearch/persistence'
require 'elasticsearch/dsl'

# an external mapping might be fetched like below:
# MAPPINGS = JSON.parse(File.read('config/elasticsearch/mappings/logs.json'), symbolize_names: true).freeze

class DashboardController < ApplicationController
  include Elasticsearch::DSL

  def index

    # for @repo constructor and initial settings look at /config/initializers/elasticsearch.rb
    # @repo sends queries to all Isoolate indexes by "*__*" index pattern,
    # in order to create a new index and populate with log data:
      # @new_repo.create_index! force: true
      # @new_repo.save(log)

    @repo = Repository.new
    @interval = '100d'

    # An example query for the last 100 day data belongs to user_id: "26" and aggregated by category name is:
      # query_definition = filter_and_agg({ "message.user_id": '26' }, '100d', 'message.category_name.keyword')

    # Below are the aggregation queries written with ElasticSearch DSL syntax for Isoolate dashboard:

    top_10_isolated_categories = filter_and_agg({ "message.isolated": 'true' }, @interval, 'message.category_name.keyword')
    top_10_allowed_categories = filter_and_agg({ "message.blocked": 'false' }, @interval, 'message.category_name.keyword')
    top_10_phishing_hostnames = filter_and_agg({ type: 'phishing' }, @interval, 'message.host.keyword')
    top_10_blocked_hostnames = filter_and_agg({ "message.blocked": 'true' }, @interval, 'message.host.keyword')
    top_10_browsed = filter_and_agg("match_all", @interval, 'message.host.keyword')
    top_10_blocked_categories = filter_and_agg({ "message.blocked": 'true' }, @interval, 'message.category_name.keyword')
    top_10_isolated_allowed_hostnames = filter_twice_and_agg({ "message.isolated": "true" }, { "message.blocked": "false"}, @interval, "message.host.keyword")

    user_logs = only_filter({"message.user_id.keyword":"26"}, @interval)

    @logs = @repo.search(user_logs)

    # bar-chart 1
    @chart_1 = bucket_data(top_10_isolated_categories)
    # bar-chart 2
    @chart_2 = bucket_data(top_10_allowed_categories)
    # column-chart-1
    @chart_3 = bucket_data(top_10_phishing_hostnames)
    # pie-chart 1
    @chart_4 = bucket_data(top_10_blocked_hostnames)
    # pie-chart 2
    @chart_5 = bucket_data(top_10_browsed)
    # bar-chart 3
    @chart_6 = bucket_data(top_10_blocked_categories)
    # bar-chart 4
    @chart_7 = bucket_data(top_10_isolated_allowed_hostnames)
  end

  # below are query methods written with DSL syntax, https://github.com/elastic/elasticsearch-ruby/tree/master/elasticsearch-dsl

  def only_filter(filter_term,interval)
    search do
      from 0
      size 100
      sort do
        by :timestamp, order: 'desc'
      end
      query do
        bool do
          filter do
            term filter_term
          end
          filter do
            range :timestamp do
              gte 'now-' + interval
            end
          end
        end
      end
    end
  end

  def filter_and_agg(filter_term, interval, agg_term)
    search do
      if filter_term == "match_all"
        query do
          bool do
            filter do
              term level:"info"
            end
            filter do
              range :timestamp do
                gte 'now-' + interval
              end
            end
          end
        end
      else
        query do
          bool do
            filter do
              term filter_term
            end
            filter do
              range :timestamp do
                gte 'now-' + interval
              end
            end
          end
        end
      end
      aggregation :my_aggregation do
        terms do
          field agg_term
        end
      end
    end
  end

  def filter_twice_and_agg(filter_term_1, filter_term_2, interval, agg_term )
    search do
      if filter_term_1 == {}
        query do
          match_all({})
        end
      else
        query do
          bool do
            filter do
              term filter_term_1
            end
            filter do
              term filter_term_2
            end
            filter do
              range :timestamp do
                gte 'now-' + interval
              end
            end
          end
        end
      end
      aggregation :my_aggregation do
        terms do
          field agg_term
        end
      end
    end
  end

  # the function converting the repsonse aggregation data into the array format Chartkick accepts
  def bucket_data(query)
    buckets = @repo.search(query).response.aggregations.my_aggregation.buckets
    buckets.map { |bucket| [bucket['key'], bucket['doc_count']] }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
  query = params[:search_posts].presence && params[:search_posts][:query]

  if query
    @posts = Post.search_published(query)
  end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.fetch(:post, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/dashboard/index.html.erb
<div class="container-fluid">

  <% #Chartkick.options = { colors: ["#63b598", "#ce7d78","#318fb5","#ea9e70","#a48a9e","#c26565","#ffd571","#b4caa0", "#b0cac7","#BF5D41"] } %>
    <% Chartkick.options = { colors: [ "#665191", "#905196", "#b85091", "#db5184","#f55a6f", "#ff6d55", "#ff8836", "#ffa600", "#ff8836","#ff6d55"] } %>

      <div class="container-fluid chart-area">

      <div id="input-area">
        <div class="input-group">
          <input type="text" class="form-control" aria-label="Text input with dropdown button">
          <div class="input-group-append">
            <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Time Range</button>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="#">Last Hour</a>
              <a class="dropdown-item" href="#">Last Day</a>
              <a class="dropdown-item" href="#">Last Week</a>
              <div role="separator" class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Choose Dates</a>
            </div>
          </div>
          <button type="button" class="btn btn-primary">
            <svg width="1em" height="1em" viewbox="0 0 16 16" class="bi bi-arrow-counterclockwise" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M12.83 6.706a5 5 0 0 0-7.103-3.16.5.5 0 1 1-.454-.892A6 6 0 1 1 2.545 5.5a.5.5 0 1 1 .91.417 5 5 0 1 0 9.375.789z"/>
              <path fill-rule="evenodd" d="M7.854.146a.5.5 0 0 0-.708 0l-2.5 2.5a.5.5 0 0 0 0 .708l2.5 2.5a.5.5 0 1 0 .708-.708L5.707 3 7.854.854a.5.5 0 0 0 0-.708z"/>
            </svg>
            Refresh
          </button>
        </div>


        <div class="row">
          <div class="col-lg-4">
            <div class="chart-card">
              <h2>Top 10 Isolated Categories</h2>
                <div class="chart">
                <%= bar_chart @chart_1, responsive: "true",id: "top_10_isolated_categories",xtitle:"Count"%>
              </div>
            </div>
          </div>

          <div class="col-lg-4">
            <div class="chart-card">
              <h2>Top 10 Allowed Categories </h2>
                <div class="chart">
                <%= bar_chart @chart_2, responsive: "true",id: "top_10_allowed_categories",xtitle:"Count"%>
              </div>
            </div>
          </div>

          <div class="col-lg-4">
            <div class="chart-card">
              <h2>Top 10 Login Allowed/Blocked Sites</h2>
              <div class="chart">
                <%= column_chart @chart_3, responsive: "true",id: "top_10_phishing_hostnames",xtitle:"Hostnames",ytitle:"Count" %>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-6 ">
            <div class="chart-card">
                <h2>Top 10 Blocked Sites</h2>
                <div class="chart">
                <%= pie_chart @chart_4, responsive: "true", id: "top_10_blocked_hostnames", donut:true, label: "doc_count", legend: "right", responsive: "true" %>
              </div>
            </div>
          </div>

          <div class="col-lg-6">
            <div class="chart-card">
                <h2>Top 10 Browsed Sites</h2>
              <div class="chart">
                <%= pie_chart @chart_5, responsive: "true", id: "top_10_browsed",  donut:true, label: "doc_count", legend: "left", responsive: "true" %>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-6 ">
            <div class="chart-card">
            <h2>Top 10 Blocked Categories</h2>
              <div class="chart">
                <%= column_chart @chart_6, responsive: "true",id: "top_10_blocked_categories", responsive: "true", ytitle:"Count"%>
              </div>
            </div>
          </div>

          <div class="col-lg-6">
            <div class="chart-card">
              <h2>Top 10 Isolated & Allowed Sites</h2>
              <div class="chart">
                <%= pie_chart @chart_7, responsive: "true",id: "top_10_isolated_allowed_hostnames", label: "doc_count", responsive: "true", legend: "left" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <% @logs.results.each do |log| %>
   <div><%=log.to_hash['timestamp'] %></div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ElasticRails</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<p>
  Press <%= link_to 'here', search_posts_path %> to search for posts.
</p>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/search.html.erb
<h1>Elastic search for posts</h1>

<%= form_for :search_posts, url: search_posts_path, method: :get do |form| %>
  <%= form.text_field :query, value: params[:search_posts].presence && params[:search_posts][:query] %>
  <%= form.submit 'Search' %>
<% end %>

<% unless @posts.nil? %>
  <% if @posts.empty? %>
    <h2>No posts found matching your query.</h2>
  <% else %>
    <h2>Search results</h2>

    <table style="width: 100%;">
      <thead>
         <tr>
           <th>Author</th>
           <th>Title</th>
           <th>Tags</th>
           <th>Published on</th>
           <th>Actions</th>
         </tr>
      </thead>

      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= post.author %></td>
            <td><%= post.title %></td>
            <td><%= post.tags %></td>
            <td><%= post.published_on %></td>
            <td><%= link_to 'View', post_path(post.id) %></td>
          </tr>
        <% end %>
      <tbody>
    </table>
  <% end %>
<% end %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>